// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: errors.proto

package errors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error int32

const (
	Error_Error_UNKNOWN Error = 0
	Error_LOOP          Error = 1
	Error_MANY_M        Error = 2
	Error_MANY_K        Error = 3
	Error_FEW_M         Error = 4
	Error_FEW_K         Error = 5
	Error_EATEN_RIGHT   Error = 6
	Error_EATEN_LEFT    Error = 7
	Error_FINISHED      Error = 8
)

// Enum value maps for Error.
var (
	Error_name = map[int32]string{
		0: "Error_UNKNOWN",
		1: "LOOP",
		2: "MANY_M",
		3: "MANY_K",
		4: "FEW_M",
		5: "FEW_K",
		6: "EATEN_RIGHT",
		7: "EATEN_LEFT",
		8: "FINISHED",
	}
	Error_value = map[string]int32{
		"Error_UNKNOWN": 0,
		"LOOP":          1,
		"MANY_M":        2,
		"MANY_K":        3,
		"FEW_M":         4,
		"FEW_K":         5,
		"EATEN_RIGHT":   6,
		"EATEN_LEFT":    7,
		"FINISHED":      8,
	}
)

func (x Error) Enum() *Error {
	p := new(Error)
	*p = x
	return p
}

func (x Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Error) Descriptor() protoreflect.EnumDescriptor {
	return file_errors_proto_enumTypes[0].Descriptor()
}

func (Error) Type() protoreflect.EnumType {
	return &file_errors_proto_enumTypes[0]
}

func (x Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Error.Descriptor instead.
func (Error) EnumDescriptor() ([]byte, []int) {
	return file_errors_proto_rawDescGZIP(), []int{0}
}

var File_errors_proto protoreflect.FileDescriptor

const file_errors_proto_rawDesc = "" +
	"\n" +
	"\ferrors.proto\x12\x06errors*\x81\x01\n" +
	"\x05Error\x12\x11\n" +
	"\rError_UNKNOWN\x10\x00\x12\b\n" +
	"\x04LOOP\x10\x01\x12\n" +
	"\n" +
	"\x06MANY_M\x10\x02\x12\n" +
	"\n" +
	"\x06MANY_K\x10\x03\x12\t\n" +
	"\x05FEW_M\x10\x04\x12\t\n" +
	"\x05FEW_K\x10\x05\x12\x0f\n" +
	"\vEATEN_RIGHT\x10\x06\x12\x0e\n" +
	"\n" +
	"EATEN_LEFT\x10\a\x12\f\n" +
	"\bFINISHED\x10\bB5Z3github.com/matbur/missionaries-and-cannibals/errorsb\x06proto3"

var (
	file_errors_proto_rawDescOnce sync.Once
	file_errors_proto_rawDescData []byte
)

func file_errors_proto_rawDescGZIP() []byte {
	file_errors_proto_rawDescOnce.Do(func() {
		file_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errors_proto_rawDesc), len(file_errors_proto_rawDesc)))
	})
	return file_errors_proto_rawDescData
}

var file_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_errors_proto_goTypes = []any{
	(Error)(0), // 0: errors.Error
}
var file_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errors_proto_init() }
func file_errors_proto_init() {
	if File_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errors_proto_rawDesc), len(file_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errors_proto_goTypes,
		DependencyIndexes: file_errors_proto_depIdxs,
		EnumInfos:         file_errors_proto_enumTypes,
	}.Build()
	File_errors_proto = out.File
	file_errors_proto_goTypes = nil
	file_errors_proto_depIdxs = nil
}
